export const titles = [
  'do androids dream of electric sheep?',
  "the hitchhiker's guide to the galaxy (hitchhiker's guide to the galaxy, #1)",
  'something wicked this way comes (green town, #2)',
  'pride and prejudice and zombies (pride and prejudice and zombies, #1)',
  'the curious incident of the dog in the night-time',
  "i was told there'd be cake: essays",
  'to kill a mockingbird',
  'the unbearable lightness of being',
  'eats, shoots & leaves: the zero tolerance approach to punctuation',
  'the hollow chocolate bunnies of the apocalypse',
  'a clockwork orange',
  "are you there, vodka? it's me, chelsea",
  'the perks of being a wallflower',
  'midnight in the garden of good and evil',
  'the man without qualities',
  'the elephant tree',
  'where the wild things are',
  'the earth, my butt, and other big round things (virginia shreves, #1)',
  'cloudy with a chance of meatballs (cloudy with a chance of meatballs, #1)',
  'one hundred years of solitude',
  'john dies at the end (john dies at the end, #1)',
  "one flew over the cuckoo's nest",
  'me talk pretty one day',
  'a heartbreaking work of staggering genius',
  "stop dressing your six-year-old like a skank: a slightly tarnished southern belle's words of wisdom",
  'the long dark tea-time of the soul (dirk gently, #2)',
  'i have no mouth and i must scream',
  'alexander and the terrible, horrible, no good, very bad day',
  'how to lose friends and alienate people',
  'the zombie room',
  "an arsonist's guide to writers' homes in new england",
  'a thousand splendid suns',
  'requiem for a dream',
  "so long, and thanks for all the fish (hitchhiker's guide to the galaxy, #4)",
  'another bullshit night in suck city',
  'a wrinkle in time (time quintet, #1)',
  'the silence of the lambs  (hannibal lecter, #2)',
  'neverwhere (london below, #1)',
  'extremely loud & incredibly close',
  'the catcher in the rye',
  'and then there were none',
  'the guernsey literary and potato peel pie society',
  'the grapes of wrath',
  "if on a winter's night a traveler",
  'trainspotting (mark renton #2)',
  'their eyes were watching god',
  'i still miss my man but my aim is getting better',
  'the man who mistook his wife for a hat and other clinical tales',
  'go the fuck to sleep',
  'the devil wears prada (the devil wears prada, #1)',
  'the zombie survival guide: complete protection from the living dead',
  'toe to toe',
  'brave new world',
  'fahrenheit 451',
  'i am america',
  'american psycho',
  'love in the time of cholera',
  'for whom the bell tolls',
  'the wasp factory',
  'fear and loathing in las vegas',
  'english as a second f*cking language: how to swear effectively, explained in detail with numerous examples taken from everyday life',
  'when you are engulfed in flames',
  'a confederacy of dunces',
  'invisible monsters',
  'treacherous estate',
  'no country for old men',
  'skagboys (mark renton #1)',
  'zen and the art of motorcycle maintenance: an inquiry into values (phaedrus, #1)',
  'factotum',
  'the gordonston ladies dog walking club (the gordonston ladies dog walking club #1)',
  'fight club',
  'lunar park',
  'the sound and the fury',
  'the moon is a harsh mistress',
  "the restaurant at the end of the universe (hitchhiker's guide to the galaxy, #2)",
  'all quiet on the western front',
  'tequila makes her clothes fall off (country music collection, #1)',
  'when will jesus bring the pork chops?',
  'the spy who came in from the cold',
  'send more idiots',
  'the man who was thursday: a nightmare',
  'the particular sadness of lemon cake',
  'as i lay dying',
  'how to shit in the woods: an environmentally sound approach to a lost art',
  'tinker, tailor, soldier, spy (george smiley, #5; karla trilogy #1)',
  'the shadow girl',
  'the electric kool-aid acid test',
  'of mice and men',
  'the lone ranger and tonto fistfight in heaven',
  'lord of the flies',
  'fuck this book',
  'the importance of being earnest',
  'making hearts',
  'what to say when you talk to yourself',
  'in our bones',
  'i hope they serve beer in hell (tucker max, #1)',
  'the last lumenian',
  'nostradamus ate my hamster',
  'hard-boiled wonderland and the end of the world',
  "life, the universe and everything (hitchhiker's guide to the galaxy, #3)",
];
